### ISSUE TITLE
Feature Request: Delete a model from the store

### ISSUE THREAD

**Issue by cdknorow** [operatorai/modelstore#113]
I've been looking through the code, maybe I just missed it. But I'm not seeing an API to delete a model that is in the store.

**Comment by nlathia** [comment]
Thanks, you're right - this doesn't exist! I can have look into how it could be done. Can you tell me any more about what motivates needing to delete a model?

**Comment by cdknorow** [comment]
Sure, I'm thinking of using this to help with storing models in s3, and keeping the meta_data in a database. However, we will often delete models and I can't have lingering files sitting around in s3, it needs to be cleaned up when a model is deleted.

**Comment by nlathia** [comment]
Sounds good!

> Also, have you thought any about the deleting model store, I was going to start working on it on my side and can submit a pull request as well.

High level, here's what I'm thinking - the two things to do is to:

1. Delete the model artefact `.tar.gz` file;
2. Delete model meta-data files so that the model doesn't get listed

For the first one, we need to:

- Add a `delete_model(domain: str, model_id: str)` function to `ModelStore` in `model_store.py`
-  This would call a `delete_model()` function in the `storage/storage.py` abstract class
-  The actual deletion would need to be implemented for each storage type (s3, etc.); maybe start with just one (`local.py`?) and leave the others with a `raise NotImplementedError()`

To remove the meta-data is a bit trickier. One simple starting point is to just delete the archive but not delete the meta-data. But then attempting to download a model that has been deleted would need to fail gracefully. Otherwise:

- The file at `_get_metadata_path(domain, model_id)` needs to be deleted;
- If the model's state has been set, then files at `_get_metadata_path(domain, model_id, state_name)` need to be deleted;
- The file at `get_domain_path()` needs to be updated 

The main edge case the comes to mind is:

- The upload function currently allows the user to upload additional files alongside the model archive; an option to delete these would need to be given too

**Comment by nlathia** [comment]
ℹ️ Am going to start working on this @cdknorow. I'm now thinking of keeping the model meta-data around, but dealing with the deleted use case somehow (updating the meta-data/setting the model to specific state) so that trying to download a model that has been deleted can be handled gracefully

**Comment by cdknorow** [comment]
@nlathia I guess deleting models can open up lots of different issues when it comes to asynchronously accessing the model_store.  Though, I think those same issues can come up with setting model state since you are using s3 as a database and don't have a locking mechanism.

For failing gracefully, are you thinking about the case where a user deletes a model, then tries to download that model again?

I think you can use the read_json_object function and wrap that file get in a try except to catch/fail gracefully on errors. 

for cloud storage, I would use the

```
try:
   get.object(model_version_metdata)
except ObjectDoesNotExists:
   raise ModelStoreObjectDeleted("This object doesn't exists"
```
   
for local, you could check if the file exists first

```
if not os.path.exists( <model_version_metadata>):
    raise ModelStoreObjectDeletedException("This object doesn't exists"
```

and just create a common exception somewhere

`class ModelStoreObjectDeletedException(Exception)`

that you raise for all cases

**Comment by nlathia** [comment]
Yep, that's similar to what I was thinking. One difference (for now) is that I was thinking of _not_ deleting the meta data files (they're very small JSON files anyway, so not a huge problem from a storage perspective). Instead of deleting the meta data files, I would treat deletion as a new type of state - so that `modelstore` can differentiate between "model ID does not exist" and "model ID used to exist and is now deleted"

**Comment by cdknorow** [comment]
@nlathia what about putting a flag in the delete to delete the metadata as well? 

My main concern from an architectural perspective is that list can never shrink. The performance is ok when you just have a few files, but if you create and delete thousands of models, then the performance is going to take a big hit.

**Comment by cdknorow** [comment]
@nlathia let me know if you want a review on the PR.

**Comment by nlathia** [comment]
@cdknorow That would be great 🙌 -- it's 90% done. I just want to add some more unit tests, but the main logic of model deletion is there.

**Comment by nlathia** [comment]
Here's what I did in the end:

- The artefact `.tar.gz` is deleted;
- The model is unset from all states
- The meta-data is copied to a special reserved state prefix/directory = we can explicitly query for deleted models, and also differentiate between (1) model deleted vs. (2) model never existed -- there are specific exceptions that can be raised 
- The meta-data is removed from the `versions` prefixes, so that it won't be read when listing models = one less read to do, slightly faster

There are a few niggles that I've left for the future:

1. Removing empty directories in the file system storage model registry;
2. Differentiating between "model never existed" and "domain never existed" (next PR);
3. Dealing with downloading the "latest" model in a domain, if that model has been deleted (needs some thought - e.g., should it revert to the one before the current latest, or should it raise an exception?)

But the main PR is now merged 🎉 so I'll close this issue. Thanks for the request & review, @cdknorow!
